# Generated by Django 4.2.1 on 2023-06-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_type', models.CharField(max_length=30)),
                ('food_description', models.CharField(blank=True, max_length=250, null=True)),
                ('food_image', models.ImageField(upload_to='')),
                ('food_ratings', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
